BASE_URL=localhost
PORT=9380
API_KEY=Ijg2ZGJlMjVlNjU3MjExZjE5MmQxYjE2ZDlmYzljN2VjIg.aiuarQ.lQqyv4nyBFNNjLRofORL5BINa_o
CHAT_ID=2f3f16ec662111f1b8890975c873e6bd
DATASET_ID=7fbba14e640f11f1aa6097f23c81cc5e
PDF_PATH=/mnt/c/Users/31326/Desktop/test.pdf
